"""empty message

Revision ID: fee1f8288602
Revises:
Create Date: 2020-06-18 14:23:59.095789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fee1f8288602'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('avi_url', sa.Text(), nullable=True),
                    sa.Column('username', sa.String(length=20),
                              nullable=False),
                    sa.Column('h_password', sa.String(length=100),
                              nullable=False),
                    sa.Column('email', sa.String(length=50), nullable=False),
                    sa.Column('bio', sa.String(length=100), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email'),
                    sa.UniqueConstraint('username')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
